INSTRUCTION_ADD = 'add'
INSTRUCTION_SUB = 'sub'
INSTRUCTION_SLL = 'sll'
INSTRUCTION_SLT = 'slt'
INSTRUCTION_SLTU = 'sltu'
INSTRUCTION_XOR = 'xor'
INSTRUCTION_SRL = 'srl'
INSTRUCTION_SRA = 'sra'
INSTRUCTION_OR = 'or'
INSTRUCTION_AND = 'and'

INSTRUCTION_ADDI = 'addi'
INSTRUCTION_SLTI = 'slti'
INSTRUCTION_SLTIU = 'sltiu'
INSTRUCTION_XORI = 'xori'
INSTRUCTION_ORI = 'ori'
INSTRUCTION_ANDI = 'andi'

INSTRUCTION_SLLI = 'slli'
INSTRUCTION_SRLI = 'srli'
INSTRUCTION_SRAI = 'srai'

INSTRUCTION_LB = 'lb'
INSTRUCTION_LH = 'lh'
INSTRUCTION_LW = 'lw'
INSTRUCTION_LBU = 'lbu'
INSTRUCTION_LHU = 'lhu'

INSTRUCTION_LUI = 'lui'
INSTRUCTION_AUIPC = 'auipc'

INSTRUCTION_BEQ = 'beq'
INSTRUCTION_BNE = 'bne'
INSTRUCTION_BLT = 'blt'
INSTRUCTION_BGE = 'bge'
INSTRUCTION_BLTU = 'bltu'
INSTRUCTION_BGEU = 'bgeu'

INSTRUCTION_SB = 'sb'
INSTRUCTION_SH = 'sh'
INSTRUCTION_SW = 'sw'

INSTRUCTION_JAL = 'jal'


R_INSTRUCTIONS = [
    INSTRUCTION_ADD, INSTRUCTION_SUB, INSTRUCTION_SLL, INSTRUCTION_SLT, INSTRUCTION_SLTU,
    INSTRUCTION_XOR, INSTRUCTION_SRL, INSTRUCTION_SRA, INSTRUCTION_OR, INSTRUCTION_AND
]

I_INSTRUCTIONS = [
    INSTRUCTION_ADDI, INSTRUCTION_SLTI, INSTRUCTION_SLTIU, INSTRUCTION_XORI, INSTRUCTION_ORI, INSTRUCTION_ANDI
]

I_SHIFT_INSTRUCTION = [INSTRUCTION_SLLI, INSTRUCTION_SRLI, INSTRUCTION_SRAI]

I_LOAD_INSTRUCTIONS = [INSTRUCTION_LB, INSTRUCTION_LH, INSTRUCTION_LW, INSTRUCTION_LBU, INSTRUCTION_LHU]

U_INSTRUCTIONS = [INSTRUCTION_LUI, INSTRUCTION_AUIPC]

B_INSTRUCTIONS = [INSTRUCTION_BEQ, INSTRUCTION_BNE, INSTRUCTION_BLT, INSTRUCTION_BGE, INSTRUCTION_BLTU, INSTRUCTION_BGEU]

S_INSTUCTIONS = [INSTRUCTION_SB, INSTRUCTION_SH, INSTRUCTION_SW]

J_INSTRUCTIONS = [INSTRUCTION_JAL]

ALL_INSTRUCTIONS = (
    R_INSTRUCTIONS + I_INSTRUCTIONS + I_SHIFT_INSTRUCTION + I_LOAD_INSTRUCTIONS +
    U_INSTRUCTIONS + B_INSTRUCTIONS + S_INSTUCTIONS + J_INSTRUCTIONS
)


R_OPCODE = '0110011'
I_LOAD_OPCODE = '0000011'
I_OPCODE = '0010011'
U_OPCODE = {
    INSTRUCTION_LUI: '0110111',
    INSTRUCTION_AUIPC: '0010111'
}
B_OPCODE = '1100011'
S_OPCODE = '0100011'
JAL_OPCODE = '1101111'

R_FUNCT3 = {
    INSTRUCTION_ADD: '000',
    INSTRUCTION_SUB: '000',
    INSTRUCTION_SLL: '001',
    INSTRUCTION_SLT: '010',
    INSTRUCTION_SLTU: '011',
    INSTRUCTION_XOR: '100',
    INSTRUCTION_SRL: '101',
    INSTRUCTION_SRA: '101',
    INSTRUCTION_OR: '110',
    INSTRUCTION_AND: '111'
}

I_LOAD_FUNCT3 = {
    INSTRUCTION_LB: '000',
    INSTRUCTION_LH: '001',
    INSTRUCTION_LW: '010',
    INSTRUCTION_LBU: '100',
    INSTRUCTION_LHU: '101'
}

I_FUNCT3 = {
    INSTRUCTION_ADDI: '000',
    INSTRUCTION_SLTI: '010',
    INSTRUCTION_SLTIU: '011',
    INSTRUCTION_XORI: '100',
    INSTRUCTION_ORI: '110',
    INSTRUCTION_ANDI: '111',
    INSTRUCTION_SLLI: '001',
    INSTRUCTION_SRLI: '101',
    INSTRUCTION_SRAI: '101'
}

B_FUNCT3 = {
    INSTRUCTION_BEQ: '000',
    INSTRUCTION_BNE: '001',
    INSTRUCTION_BLT: '100',
    INSTRUCTION_BGE: '101',
    INSTRUCTION_BLTU: '110',
    INSTRUCTION_BGEU: '111'
}

S_FUNCT3 = {
    INSTRUCTION_SB: '000',
    INSTRUCTION_SH: '001',
    INSTRUCTION_SW: '010'
}


R_FUNCT7 = {
    INSTRUCTION_ADD: '0000000',
    INSTRUCTION_SUB: '0100000',
    INSTRUCTION_SLL: '0000000',
    INSTRUCTION_SLT: '0000000',
    INSTRUCTION_SLTU: '0000000',
    INSTRUCTION_XOR: '0000000',
    INSTRUCTION_SRL: '0000000',
    INSTRUCTION_SRA: '0100000',
    INSTRUCTION_OR: '0000000',
    INSTRUCTION_AND: '0000000'
}

I_SHIFT_FUNCT7 = {
    INSTRUCTION_SLLI: '0000000',
    INSTRUCTION_SRLI: '0000000',
    INSTRUCTION_SRAI: '0100000'
}
